# ============================================================
# 用户服务配置
# ============================================================
server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_interview?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true
    baseline-on-migrate: true          # 对已有数据库做基线，不会覆盖已有表
    baseline-version: 1
    locations: classpath:db/migration  # 默认值，可省略
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
